server:
  forward-headers-strategy: FRAMEWORK
  servlet:
    context-path: /app

spring:
  application:
    name: oauth-demo
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: "${GOOGLE-CLIENT-SECRET}"
            client-id: "${GOOGLE_CLIENT_ID}"
            scope:
            - openid
            - profile
            - email
